//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grumpy.RipplesMQ.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageState
    {
        public int Id { get; set; }
        public string MessageId { get; set; }
        public string SubscriberName { get; set; }
        public string State { get; set; }
        public int ErrorCount { get; set; }
        public System.DateTimeOffset UpdateDateTime { get; set; }
    }
}
