//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grumpy.RipplesMQ.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBrokerService
    {
        public string ServerName { get; set; }
        public string ServiceName { get; set; }
        public string InstanceName { get; set; }
        public string RemoteQueueName { get; set; }
        public string LocaleQueueName { get; set; }
        public System.DateTimeOffset LastStartDateTime { get; set; }
    }
}
