//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grumpy.RipplesMQ.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string Id { get; set; }
        public string Topic { get; set; }
        public string Type { get; set; }
        public string Body { get; set; }
        public System.DateTimeOffset PublishDateTime { get; set; }
    }
}
