//--------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------

namespace Grumpy.RipplesMQ.Entity
{
    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Logging.Abstractions;
    using Grumpy.Entity.Interfaces;
    using Grumpy.Logging;

    public partial class Entities
    {
	    public ILogger Logger { get; } = NullLogger.Instance;

        public Entities(ILogger logger, IEntityConnectionConfig entityConnectionConfig) : base(entityConnectionConfig.ConnectionString("Grumpy.RipplesMQ.Entity", "Model"))
        {
		    Logger = logger;
			Logger.Information("Creating Context for Entities {%ConnectionString}", entityConnectionConfig.ConnectionString("Grumpy.RipplesMQ.Entity", "Model"));

            EntityFrameworkReferenceHack();
        }

        public Entities(IEntityConnectionConfig entityConnectionConfig) : base(entityConnectionConfig.ConnectionString("Grumpy.RipplesMQ.Entity", "Model"))
        {
            EntityFrameworkReferenceHack();
        }

        private void EntityFrameworkReferenceHack()
        {
#pragma warning disable S1481
            // NOTE: Using type from EntityFramework.SqlServer to ensure copy of dll to all application using this dll
            // ReSharper disable once UnusedVariable
            var instance = System.Data.Entity.SqlServer.SqlProviderServices.Instance;
#pragma warning restore S1481
        }
    }
}
