//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grumpy.RipplesMQ.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public string Name { get; set; }
        public string Topic { get; set; }
        public string ServerName { get; set; }
        public string ServiceName { get; set; }
        public string QueueName { get; set; }
        public System.DateTimeOffset RegisterDateTime { get; set; }
        public System.DateTimeOffset PulseDateTime { get; set; }
    }
}
